name: Check TensorFlow.js Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check TensorFlow.js Installation
        run: |
          npm install @tensorflow/tfjs
          node -e "require('@tensorflow/tfjs'); console.log('TensorFlow.js installed successfully');"
