name: Check TensorFlow.js Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-tensorflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Check TensorFlow.js Installation
      run: |
        npm list @tensorflow/tfjs
        node -e "require('@tensorflow/tfjs'); console.log('TensorFlow.js is installed and working properly');"
